### PR TITLE
Appstore

### PR DESCRIPTION
**Pull request by philippm**
Hi Tim,

I noticed that in the appstore branch the checkboxes no longer showed (at least under 10.6, not tested under 10.5).

This commit should fix this problem, but uses a different, slightly slower solution to circumvent the private _normalImage ivar.

### CODE REVIEW

**Comment by timthedevguy** [comment]
the current branch should work perfectly fine, if your checkboxes aren't appearing in an already existing project you will need to toggle the Bezel Type from Radio to Check or Check to Radio and back again, this sets up the new code I included in the last commit.

Please let me know if this works for you, it has for everyone else.  I put this info in the commit messages but not in the readme yet, sorry about that.

**Comment by timthedevguy** [comment]
Pilllppm,

I replied before I read the actual code changes, thats an interesting method to approach the problem, when you say slower...would it be noticeable?  It seems like it may be cleaner than actually interfering with the setValue:ForKey: method.

Thanks,
Tim

**Comment by philippm** [comment]
Hi Tim,

First of all thank you for making the fixes to BGHUDAppKit so quickly. Without them I couldn't have submitted our app to the app store today, and I really appreciate your time.

As for your comment: thanks for pointing out the need to toggle the bezel type -- I should have read all the docs first.

I don't think the slightly slower implementation would be noticeable, unless you have very large matrices or tables that host button cells. It works fine for the handful of elements we use in Archiver (http://archiverapp.com).

What I should have pointed out is that I haven't tested the code under 10.5. I should and would normally have done this but I wanted to submit the app to the App Store before the end of the year, and wanted other people to benefit from the fix.

**Comment by timthedevguy** [comment]
Philippm,

No problem, hope you didn't think I was being short with ya before, had my 7 year old and his dog running about driving me nuts, was just trying to reply quick as possible.

I just got the update the other day, from Rucksack to Archiver, nice to hear it's going in the app store.

Everything should work under 10.5, I don't see why it wouldn't.  I'll play with your code some on Sunday when my boy goes back to his mothers and I can think again. lol

Thanks
Tim

**Pull request closed without merging**
