### PR TITLE
memory leak fix

### PR DESCRIPTION
**Pull request by niltsh**
I am not the fix is proper, but I saw the "path" is released elsewhere.

### CODE REVIEW

**Comment by timthedevguy** [comment]
Good catch, I'll pull it in now!

**Comment by niltsh** [comment]
Hi, sorry for bothering.

I thought you must be busy with the appstore issue.

I just download src in the master, and use the static analysis in Xcode simply.
Actually there are 10 warnings from Xcode, and I just fix only 2 of them, since I really do not how to use git.
I edited the src in the browser...

So actually, the pull request is a just remind. : )

I have my own personal project, which is a media player called MPlayerX.
http://code.google.com/p/mplayerx/

MPlayerX uses your framework heavily.
So if there are something I could contribute, I feel honored.

And still, there are 8 left...

**Comment by timthedevguy** [comment]
niltsh,

No problem, I'll run the Static Analyser and see what pops up, thanks for the information :)  And your MPlayerX looks pretty awesome so far, like what you did with the color/hue shader.

**Comment by timthedevguy** [comment]
nitsh,

This may be a stupid question but how did you set up your static analyse?  I tried and I don't get any errors so I must be doing something wrong.

EDIT: I figured it out, lol, I'll get the errors fixed

**Comment by niltsh** [comment]
the basic settings of the project I have changed are
1. Architectures  -> Standard (32/64-bit Universal)
2. Base SDK  -> Mac OS X 10.5
3. C/C++ Compiler Version -> LLVM compiler 1.5

I thought LLVM was the key.

**Pull request merged**
